'use client'

import { useState, useTransition } from 'react'
import { saveCow, saveDonation, saveUpdate, deleteCow, deleteDonation, deleteUpdate } from '@/app/admin/dashboard/actions'

type Item = Record<string, string | number | null>
type Props = { initial: { donations: Item[]; cows: Item[]; updates: Item[] } }
const tabs = [['donations', 'Donations'], ['cows', 'Cow adoptions'], ['updates', 'Sanctuary updates']] as const

export function AdminCrud({ initial }: Props) {
  const [data, setData] = useState(initial); const [active, setActive] = useState<(typeof tabs)[number][0]>('donations'); const [editing, setEditing] = useState<Item | null>(null); const [pending, start] = useTransition(); const [notice, setNotice] = useState('')
  const fields: Record<string, string[]> = { donations: ['title', 'badgeCategory', 'priceInr', 'description', 'imageUrl'], cows: ['name', 'ageAndStatus', 'description', 'imageUrl'], updates: ['title', 'dateLabel', 'summary', 'imageUrl'] }
  const labels: Record<string, string> = { title: 'Title', badgeCategory: 'Category', priceInr: 'Price (INR)', description: 'Description', imageUrl: 'Image URL', name: 'Cow name', ageAndStatus: 'Age and status', dateLabel: 'Date label', summary: 'Summary' }
  const save = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const raw = Object.fromEntries(new FormData(event.currentTarget)); const item = { ...raw, ...(active === 'donations' ? { priceInr: Number(raw.priceInr) } : {}), id: editing?.id as string | undefined } as never; start(async () => { const fn = active === 'donations' ? saveDonation : active === 'cows' ? saveCow : saveUpdate; await fn(item); setNotice('Saved and published'); setEditing(null); window.location.reload() }) }
  const remove = (id: string) => { if (!confirm('Delete this item?')) return; start(async () => { const fn = active === 'donations' ? deleteDonation : active === 'cows' ? deleteCow : deleteUpdate; await fn(id); setNotice('Deleted'); setData((current) => ({ ...current, [active]: current[active].filter((row) => row.id !== id) })) }) }
  return <section><nav className="flex flex-wrap gap-2 border-b border-border pb-4">{tabs.map(([key, label]) => <button key={key} onClick={() => { setActive(key); setEditing(null) }} className={`rounded-full px-4 py-2 text-sm font-bold ${active === key ? 'bg-primary text-primary-foreground' : 'bg-secondary text-primary'}`}>{label} ({data[key].length})</button>)}</nav><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-3">{data[active].map((row) => <article key={String(row.id)} className="flex items-center justify-between gap-4 rounded-2xl border border-border bg-card p-4"><div><p className="font-bold text-primary">{String(row.title ?? row.name)}</p><p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{String(row.description ?? row.summary ?? row.ageAndStatus ?? '')}</p></div><div className="flex shrink-0 gap-2"><button onClick={() => setEditing(row)} className="rounded-full border border-border px-3 py-2 text-xs font-bold text-primary">Edit</button><button onClick={() => remove(String(row.id))} disabled={pending} className="rounded-full bg-destructive/10 px-3 py-2 text-xs font-bold text-destructive">Delete</button></div></article>)}{!data[active].length && <div className="rounded-2xl border border-dashed border-border p-10 text-center text-sm text-muted-foreground">No records yet. Add your first item.</div>}</div><form onSubmit={save} className="rounded-3xl border border-border bg-card p-5"><h2 className="font-serif text-2xl text-primary">{editing ? 'Edit item' : 'Add new item'}</h2>{fields[active].map((field) => <label key={field} className="mt-4 block text-xs font-bold text-primary">{labels[field]}{field === 'description' || field === 'summary' ? <textarea name={field} defaultValue={String(editing?.[field] ?? '')} required className="mt-2 min-h-24 w-full rounded-xl border border-border bg-background px-3 py-2 text-sm font-normal outline-none focus:ring-2 focus:ring-accent" /> : <input name={field} type={field === 'priceInr' ? 'number' : 'text'} defaultValue={String(editing?.[field] ?? '')} required={field !== 'imageUrl'} className="mt-2 w-full rounded-xl border border-border bg-background px-3 py-2 text-sm font-normal outline-none focus:ring-2 focus:ring-accent" />}</label>)}<div className="mt-6 flex gap-2"><button disabled={pending} className="rounded-full bg-primary px-5 py-3 text-sm font-bold text-primary-foreground">{pending ? 'Saving…' : 'Save & publish'}</button>{editing && <button type="button" onClick={() => setEditing(null)} className="rounded-full border border-border px-5 py-3 text-sm font-bold text-primary">Cancel</button>}</div>{notice && <p className="mt-3 text-sm font-semibold text-accent-foreground">{notice}</p>}</form></div></section>
}
